// Login action
export const TRY_LOGIN = 'TRY_LOGIN';
export const TRY_LOGIN_SUCCESS = 'TRY_LOGIN_SUCCESS';
export const TRY_LOGIN_FAILED = 'TRY_LOGIN_FAILED';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

//civil id
export const CIVIL_ID_SEND = 'CIVIL_ID_SEND';
export const CIVIL_ID_SENT = 'CIVIL_ID_SENT';
export const SET_CIVIL_INFORMATION = 'SET_CIVIL_INFORMATION';

// phone number
export const PHONE_NUMBER_SEND = 'PHONE_NUMBER_SEND';
export const PHONE_NUMBER_SENT = 'PHONE_NUMBER_SENT';

// OTP
export const SEND_OTP = 'SEND_OTP';
export const OTP_SENT = 'OTP_SENT';

// register action
export const SEND_REGISTER = 'SEND_REGISTER';
export const REGISTER_SENT = 'REGISTER_SENT';

export const TRY_REGISTER_SUCCESS = 'TRY_REGISTER_SUCCESS';
export const TRY_REGISTER_FAILED = 'TRY_REGISTER_FAILED';
export const SEND_CHECK_ISREGISTERED = 'SEND_CHECK_ISREGISTERED';
export const CHECK_ISREGISTERED_SENT = 'CHECK_ISREGISTERED_SENT';

// areas
export const SEND_AREAS = 'SEND_AREAS';
export const AREAS_SENT = 'AREAS_SENT';

//health state
export const SEND_HEALTH_STATE = 'SEND_HEALTH_STATE';
export const HEALTH_STATE_SENT = 'HEALTH_STATE_SENT';

//survey
export const HEALTH_SURVEY_SHOWN = 'HEALTH_SURVEY_SHOWN';
export const CHANGED_ANSWER = 'CHANGED_ANSWER';
export const CHANGED_ANSWER_YES_NO = 'CHANGED_ANSWER_YES_NO';
export const SEND_SURVEY = 'SEND_SURVEY';
export const SURVEY_SENT = 'SURVEY_SENT';

//Status List
export const FETCH_STATUS_CATEGORIES = 'FETCH_STATUS_CATEGORIES';
export const FETCH_STATUS_CATEGORIES_SUCCESS =
  'FETCH_STATUS_CATEGORIES_SUCCESS';
export const FETCH_STATUS_CATEGORIES_FAILED = 'FETCH_STATUS_CATEGORIES_FAILED';

//Questions
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_FETCHED = 'FETCH_QUESTIONS_FETCHED';

export const SUBMIT_ANSWERS = 'SUBMIT_ANSWERS';
export const SUBMIT_ANSWERS_SUCCESS = 'SUBMIT_ANSWERS_SUCCESS';
export const SUBMIT_ANSWERS_FETCHED = 'SUBMIT_ANSWERS_FETCHED';

//location
export const SEND_LOCATION = 'SEND_LOCATION';
export const LOCATION_SENT = 'LOCATION_SENT';

//temperature
export const TEMPERATURE_MODAL_SHOWN = 'TEMPERATURE_MODAL_SHOWN';
export const SEND_TEMPERATURE = 'SEND_TEMPERATURE';
export const TEMPERATURE_SENT = 'TEMPERATURE_SENT';
export const TEMPERATURE_RESET = 'TEMPERATURE_RESET';

//possible infections
export const POSSIBLE_INFECTIONS_MODAL_SHOWN =
  'POSSIBLE_INFECTIONS_MODAL_SHOWN';
export const SEND_POSSIBLE_INFECTIONS = 'SEND_POSSIBLE_INFECTIONS';
export const POSSIBLE_INFECTIONS_SENT = 'POSSIBLE_INFECTIONS_SENT';

//request
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const REQUEST_STARTED = 'REQUEST_STARTED';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';

//errors
export const HIDE_ERROR = 'HIDE_ERROR';
export const SHOW_ERROR = 'SHOW_ERROR';

//remaining Days
export const FETCH_REMAINING_DAYS = 'FETCH_REMAINING_DAYS';
export const FETCH_REMAINING_DAYS_SUCCESS = 'FETCH_REMAINING_DAYS_SUCCESS';
export const FETCH_REMAINING_DAYS_FAILED = 'FETCH_REMAINING_DAYS_FAILED';

//
export const ANSWER_QUESTION = 'ANSWER_QUESTION';
//location
export const SEND_GET_LOCATION = 'SEND_GET_LOCATION';
export const GET_LOCATION_SENT = 'GET_LOCATION_SENT';
export const SEND_UPDATE_LOCATION = 'SEND_UPDATE_LOCATION';
export const UPDATE_LOCATION_SENT = 'UPDATE_LOCATION_SENT';

export const SET_AS_BACKGROUND_FETCH = 'SET_AS_BACKGROUND_FETCH';
